### ISSUE TITLE
Problem with RAW mod

### ISSUE THREAD

**Issue by wycjam** [FetzenRndy/GtaRagePlugins#1]
Installed correctly but nothing happens in game when button is pressed.

**Comment by PatrickHollweck** [comment]
Thanks for reporting, I somehow missed this issue.... Sorry

I am looking into it.

**Comment by PatrickHollweck** [comment]
@wycjam Can you confirm the plugin works with the new version ?

**Comment by wycjam** [comment]
Nevermind, works good.
