### ISSUE TITLE
Suggestion: Ability to use modifier keys

### ISSUE THREAD

**Issue by waynieoaks** [FetzenRndy/GtaRagePlugins#2]
Hi

Would it be possible to use modifiers, for example to use Ctrl + R to activate?

Many thanks in advance.

**Comment by PatrickHollweck** [comment]
Sorry for the late response... For some reason I do not get notifications...

Will implement this today :)

**Comment by PatrickHollweck** [comment]
Well I got have this implemented. The problem is that I kinda lost my credentials to my lspdfr.com account so I cant upload it until I resolve this......

You can either build from source, Or I provide a "Release" for this on github.
Also gotta push those commits then..
